# font 
font_family                 SFMono Nerd Font Regular
font_size                   12.0
text_composition_strategy   legacy

# os window
macos_titlebar_color background

# cursor
cursor_shape            block
shell_integration       enabled no-cursor
cursor_blink_interval   0


# color scheme
include ./nord.conf
