# Nord Colorscheme for Kitty
# Based on:
# - https://gist.github.com/marcusramberg/64010234c95a93d953e8c79fdaf94192
# - https://github.com/arcticicestudio/nord-hyper

foreground            #bbc3d4
background            #242933
selection_foreground  #000000
selection_background  #FFFACD
url_color             #0087BD
cursor                #81A1C1

# black
color0   #191c24
color8   #727072

# red
color1   #bf616a
color9   #d06f79

# green
color2   #a3be8c
color10  #b1d196

# yellow
color3   #ebcb8b
color11  #f0d399

# blue
color4  #81a1c1
color12 #8cafd2

# magenta
color5   #b48ead
color13  #c895bf

# cyan
color6   #8fbcbb
color14  #93ccdc

# white
color7   #bbc3d4
color15  #bbc3d4
